menu:
  - text: 首页
    link: /
    icon: home
  - text: 归档
    link: /archive
    icon: archive
  - text: 分类
    link: javascript:;
    icon: bookmark
  - text: 读书
    link: /book
    icon: book
  - text: 关于
    link: /about
    icon: user

excerpt_link: Read More
archive_yearly: true

user:
  name: 林寿山
  desc: Web前端/游戏开发
  avatar: http://tp2.sinaimg.cn/1956184117/180/5674436546/1
  
copyright: © 2016 raytaylorlin.com, All rights reserved.

social:
  weibo: http://weibo.com/1956184117
  github: https://github.com/raytaylorlin

disqus_shortname:
duoshuo_shortname: raytaylorlin

# Google分析track id
google_analytics:

# 是否开启prettify.js美化代码
google_code_prettify: true
# 高亮的主题，若为空则使用默认主题
google_code_prettify_theme: prettify-tomorrow-night-eighties
rss:
