menu:
    首页: /
    存档: /archives
    读书: /reading
    关于: /about

menu_icon:
    首页: icon-home
    存档: icon-archive
    读书: icon-book
    关于: icon-user

menu_id:
    首页: id-home
    存档: id-archive
    读书: id-reading
    关于: id-about

excerpt_link: Read More
archive_yearly: true

# widgets:
#     - category

weibo_url: http://weibo.com/1956184117
renren_url: http://www.renren.com/309069699
github_url: https://github.com/raytaylorlin

blogrolls:
    - Ray Taylor Lin's Blog: http://raytaylorlin.com/

google_analytics_track_id: UA-43460643-1
google_analytics_website: http://raytaylorlin.com

# 是否开启prettify.js美化代码
google_code_prettify: true
# 高亮的主题，若为空则使用默认主题
google_code_prettify_theme: prettify_raytaylorism
rss:
