menu:
    首页: /
    归档: /archives
    分类: javascript:void(0);
    读书: /reading
    关于: /about

menu_icon:
    首页: home
    归档: archive
    分类: archive
    读书: book
    关于: user

menu_class:
    首页: menu-home
    归档: menu-archive
    分类: menu-category
    读书: menu-reading
    关于: menu-about

excerpt_link: Read More
archive_yearly: true

# widgets:
#     - category
copyright: © 2016 raytaylorlin.com, All rights reserved.

weibo_url: http://weibo.com/1956184117
renren_url: http://www.renren.com/309069699
github_url: https://github.com/raytaylorlin
google_plus_url: https://plus.google.com/113216251417550089742?rel=author

disqus_shortname:
duoshuo_shortname: raytaylorlin

# Google分析track id
google_analytics:

# 是否开启prettify.js美化代码
google_code_prettify: true
# 高亮的主题，若为空则使用默认主题
google_code_prettify_theme: prettify-tomorrow-night-eighties
rss:
