menu:
  Home: /
  Archives: /archives

excerpt_link: Read More

widgets:
  - category
  - tag
  - tagcloud
  - recent_posts
  - blogroll

blogrolls:
  - Heroic Yang's Blog: http://heroicyang.com/

fancybox: true

duoshuo_shortname: 

google_analytics:
rss:
