menu:
    首页: /
    存档: /archives

menu_icon:
    首页: icon-home
    存档: icon-archive

excerpt_link: Read More
archive_yearly: true

widgets:
    - category

weibo_url: http://weibo.com/1956184117
renren_url: http://www.renren.com/309069699
github_url: https://github.com/raytaylorlin

blogrolls:
    - Ray Taylor Lin's Blog: http://raytaylorlin.com/

google_analytics_track_id: UA-43460643-1
google_analytics_website: http://raytaylorlin.com
rss:
