menu:
    首页: /
    存档: /archives

menu_icon:
    首页: icon-home
    存档: icon-archive

excerpt_link: Read More
archive_yearly: false

widgets:
    - category

blogrolls:
    - Heroic Yang's Blog: http://heroicyang.com/

duoshuo_shortname: raytaylorlin

google_analytics:
rss:
