menu:
    首页: /
    存档: /archives

menu_icon:
    首页: icon-home
    存档: icon-archive

excerpt_link: Read More
archive_yearly: false

widgets:
    - category

weibo_url: http://weibo.com/1956184117
renren_url: http://www.renren.com/309069699
github_url: https://github.com/raytaylorlin

blogrolls:
    - Ray Taylor Lin's Blog: http://raytaylorlin.com/

duoshuo_shortname: raytaylorlin

google_analytics:
rss:
