menu:
  首页: /
  归档: /archives

excerpt_link: Read More
archive_yearly: false

widgets:
  - category

blogrolls:
  - Heroic Yang's Blog: http://heroicyang.com/

fancybox: true

duoshuo_shortname: raytaylorlin

google_analytics:
rss:
